version: '3.8'

services:
  app:
    build: .  # Build from local Dockerfile
    hostname: tasty
    ports:
      - 8001:80
    volumes:
      - ./media:/var/www/persistent-media:rw
    environment:
      - APP_ENV=production
      - APP_URL=http://127.0.0.1:8001   #CHANGEME
                                        # Replace with your server's public IP address
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=tastyigniter
      - DB_USERNAME=tastyigniter
      - DB_PASSWORD=securefassword      #CHANGEME
                                        # Replace with your database password
      - CACHE_DRIVER=redis
      - REDIS_HOST=redis
      - MAILGUN_DOMAIN=default
      - MAILGUN_SECRET=default
      - MAILGUN_ENDPOINT=api.eu.mailgun.net

    restart: always
  db:
    image: mariadb:10.11
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=tastyigniter
      - MYSQL_USER=tastyigniter
      - MYSQL_PASSWORD=securefassword   #CHANGEME
                                        # Replace with your database password
                                        # Has to be the same as in the app service
    restart: always

  redis:
    image: redis:7
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: always